#
# Mining Strategy
# Two available: PositionMiner, NaiveMiner
#
mining_strategy: PositionMiner

#
# datafile path relative to app root
#
datafile:
    production: #{datafile_production}
    development: #{datafile_development}
    test: spec/fixtures/datafile_test