# Gemfile
source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'puma'

group :test, :development do
  gem 'rake'
end

group :test do
  gem 'rack-test'
  gem 'rspec', '3.1.0'
  gem 'rspec-mocks', '3.1.1'
end
